In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np 

NumPy Arrays

In [2]:
np.array([1,2])

array([1, 2])

In [4]:
matrix=[[1,2,3],[3,2,1],[0,9,8]]
matrix

[[1, 2, 3], [3, 2, 1], [0, 9, 8]]

In [5]:
np.array(matrix)

array([[1, 2, 3],
       [3, 2, 1],
       [0, 9, 8]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
np.linspace(0,10,4) #evenly spaced numbers between 0 and 10

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [10]:
np.eye(4) #4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.zeros(5,dtype='int8')

array([0, 0, 0, 0, 0], dtype=int8)

In [14]:
np.random.rand(2) #from 0 to 1

array([0.13544581, 0.84698683])

In [15]:
np.random.rand(5,5) #matrix of random numbers from 0 to 1

array([[0.48131886, 0.50545141, 0.62379067, 0.91200634, 0.12565039],
       [0.95591116, 0.17559661, 0.09101505, 0.63997175, 0.04241089],
       [0.25712139, 0.64251044, 0.79458092, 0.16631996, 0.6810156 ],
       [0.61664031, 0.63238775, 0.06586637, 0.54719609, 0.95001002],
       [0.41735262, 0.36934161, 0.12914136, 0.36413825, 0.49512257]])

In [16]:
np.random.randn(5,5)

array([[ 1.61048451, -2.47917661, -0.88470414, -0.49430397, -0.18384234],
       [ 1.40654986, -1.5792814 ,  0.2869221 , -1.3936985 ,  0.5632744 ],
       [-0.84179516, -2.09191422, -1.07088295,  0.45157329, -1.19792245],
       [ 0.629473  ,  0.52818436,  2.61392441,  0.87628131,  0.55510431],
       [-1.60877788,  1.76290804, -0.77037346,  1.37286553,  1.68322274]])

In [18]:
np.random.randint(1,100,10) #10 random numbers include 1, exlcude 100

array([94, 50, 38, 72, 36, 97, 94, 82, 30, 75])

In [24]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [29]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[0]

0

In [31]:
arr[1:5] #1 is included, 5 is excluded

array([1, 2, 3, 4])

In [32]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [33]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [34]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
arr[0:5]=100 #broadcasting value 100 from index 0 upto but not including 5
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [36]:
arr[:]=99 #all changes are done in original data, no copy is made
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [37]:
newarr=np.arange(0,11)
newarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
cpy=newarr.copy()
cpy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
cpy[:]=10 #broadcasting
cpy

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [40]:
a2d=np.array(([1,2,3],[4,5,6],[7,8,9])) #numpy array can be multidimensional
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a2d[1] #indexing in 2d

array([4, 5, 6])

In [42]:
a2d[0][2]

3

In [45]:
a2d[2,1]

8

In [46]:
a2d[:2,1:] #everything upto but not including row 2

array([[2, 3],
       [5, 6]])

In [47]:
newarr>4 #checking 

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [48]:
boolarray=newarr<6
boolarray

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [49]:
newarr[boolarray] #displays the true results

array([0, 1, 2, 3, 4, 5])

Numpy arithmetic Operations

In [50]:
a1=np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a1+a1 #matrix addition takes place-element by element addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
a1-a1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
a1*a1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [54]:
a1**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [55]:
np.sqrt(a1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [56]:
np.max(a1)

9